name: Build and deploy Angular app

on:
  push:
    branches:
      - main
      - developer
  workflow_dispatch:

jobs:
  build-beta:
    if: github.ref == 'refs/heads/developer'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Create and switch to beta branch
        run: |
          if git show-ref --verify --quiet refs/heads/beta; then
            git checkout beta
          else
            git checkout --orphan beta
          fi
      - name: Copy dist folder to beta branch
        run: |
          PROJECT_NAME=$(ls dist)
          find . -mindepth 1 -maxdepth 1 ! -name 'dist' ! -name '.git' -exec rm -rf {} \;
          cp -r dist/$PROJECT_NAME/* .
          rm -rf dist
          git add .
          git commit -m "Add build artifacts"
      - name: Push changes to beta branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: beta
          force: true
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: deploy_dist
          path: dist/

  build-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Create and switch to production branch
        run: |
          if git show-ref --verify --quiet refs/heads/production; then
            git checkout production
          else
            git checkout --orphan production
          fi
      - name: Copy dist folder to production branch
        run: |
          PROJECT_NAME=$(ls dist)
          find . -mindepth 1 -maxdepth 1 ! -name 'dist' ! -name '.git' -exec rm -rf {} \;
          cp -r dist/$PROJECT_NAME/* .
          rm -rf dist
          git add .
          git commit -m "Add build artifacts"
      - name: Push changes to production branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: production
          force: true
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: deploy_dist
          path: dist/
